# prometheus.yaml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'zookeeper'
    static_configs:
      - targets: ['172.16.10.1:7001','172.16.10.2:7002','172.16.10.3:7003','172.16.10.4:7004','172.16.10.5:7005']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - '/etc/prometheus/rules.yaml'
  - '/etc/prometheus/recording_rules.yaml'